pipeline {
    agent any

    triggers {
        pollSCM('* * * * *')
    }

    stages {
        stage('Test') {
            steps {
                dir('RA5/RA5_1/assets/code') {
                    sh 'python3 test_calculadora.py'
                }
            }
        }
    }
}


