pipeline {
    agent any

    triggers {
        pollSCM('* * * * *') // Comprueba cada minuto si hay cambios
    }

    stages {
        stage('Test') {
            steps {
                dir('RA5_1/assets/code') {
                    sh 'python3 -m unittest test_calculadora.py'
                }
            }
        }
    }
}

